### ISSUE TITLE
Popups not rendering

### ISSUE THREAD

**Issue by DanielKim1** [sunrisemovement/sunrise-movement-hub-map#5]
Reproduction:
1. Go to https://www.sunrisemovement.org/
2. Click on any anchor element in the list of hubs (e.g. "Sunrise Birmingham")

Expected:
<img width="285" alt="Screen Shot 2020-01-15 at 11 29 55 PM" src="https://user-images.githubusercontent.com/22206686/72493424-f6c3e980-37ee-11ea-9f42-8c068b2c86a7.png">

Observed:
- The popup does not render
- The following error message displays in the browser console:
```
Uncaught TypeError: Cannot read property 'style' of undefined
    at r.<anonymous> ((index):1225)
    at r.St.fire (evented.js:115)
    at r.resize (map.js:535)
    at r._onWindowResize (map.js:2062)
```

The error happens at this function:
```
  map.on('moveend', function() {
    var my = $('#hub-map .mapboxgl-popup')[0];
    my.style.transform = my.style.transform.replace("-50%", "calc(-50% - 0.5px)");
  });
```
However, the previous code is not in this repository.

It appears that because this error is thrown in `flyToStore`, `createPopUp` is never run.

Proposed fixes:
1. run `createPopUp` before `flyToStore` in the click event handlers of `link` and `el`
2. edit the map on moveend function:
```
  map.on('moveend', function() {
    var my = $('#hub-map .mapboxgl-popup')[0];
    if (typeof my !== "undefined") my.style.transform = my.style.transform.replace("-50%", "calc(-50% - 0.5px)");
  });
```

**Comment by asross** [comment]
@DanielKim1 thanks for the issue! Although I'm unable to replicate this problem, it totally seems reasonable (maybe a race condition?) and I definitely agree that at least adding the undefined check makes sense.

The new home for the hub map code is actually at https://github.com/sunrisemovement/hubhub, specifically https://github.com/sunrisemovement/hubhub/blob/master/public/hub_map.html. I'll go ahead and make the null-safety update you suggested there and test out the reordering of `createPopUp` and `flyToStore` -- there might be another solution.

**Comment by asross** [comment]
Actually, on second thought, the re-ordering you suggested makes more sense / looks better anyway :)

Merged those changes in https://github.com/sunrisemovement/hubhub/pull/6, will deploy to the main site shortly.

**Comment by DanielKim1** [comment]
Awesome, thank you!
